services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=temp'
      - 'MYSQL_PASSWORD=butler'
      - 'MYSQL_ROOT_PASSWORD=butler'
      - 'MYSQL_USER=butler'
    ports:
      - '3306'
